services:
  fastapi: #Nome do serviço para o backend
    build: ./backend #Diz onde esse serviço vai operar
    ports: 
      - "8000:8000" #Mapeia [Porta da sua Máquina]:[Porta do Container]
    volumes:
      - ./backend:/app #Mapeia o diretório do código para dentro do container
    env_file:
      - .env
    depends_on:
      - db
      

  react: #Nome do serviço para o frontend
    build: ./frontend #Diz onde esse serviço vai operar
    ports:
      - "5173:5173" #Mapeia [Porta da sua Máquina]:[Porta do Container]
    volumes:
      - ./frontend:/app #Mapeia o diretório do código para dentro do container
      - /app/node_modules # Evita que o node_modules do host sobrescreva o do container
    environment:
      - VITE_API_URL=http://localhost:8000 #URL da API para o frontend
    
  db: #Nome do serviço para o banco de dados
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: #Volume para persistência dos dados do PostgreSQL