"""initial tables

Revision ID: e0ae064dcb22
Revises: 
Create Date: 2026-02-17 01:50:30.107498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0ae064dcb22'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('vagas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('cargo', sa.String(), nullable=False),
    sa.Column('jornada', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('salario', sa.Float(), nullable=False),
    sa.Column('local', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('requisitos', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vagas_id'), 'vagas', ['id'], unique=False)
    op.create_table('candidatos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('cargo_atual', sa.String(), nullable=False),
    sa.Column('area_atual', sa.String(), nullable=False),
    sa.Column('conhecimentos', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_usuario')
    )
    op.create_index(op.f('ix_candidatos_id'), 'candidatos', ['id'], unique=False)
    op.create_table('candidatura',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_vaga', sa.Integer(), nullable=True),
    sa.Column('id_candidato', sa.Integer(), nullable=True),
    sa.Column('afinidade', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_candidato'], ['candidatos.id'], ),
    sa.ForeignKeyConstraint(['id_vaga'], ['vagas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidatura_id'), 'candidatura', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidatura_id'), table_name='candidatura')
    op.drop_table('candidatura')
    op.drop_index(op.f('ix_candidatos_id'), table_name='candidatos')
    op.drop_table('candidatos')
    op.drop_index(op.f('ix_vagas_id'), table_name='vagas')
    op.drop_table('vagas')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
